spring:
  datasource:
    url: jdbc:postgresql://localhost/landmarkist
    username: user
    password: password

  data:
    rest:
      base-path: /api

  database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect