spring:
  datasource:
    url: jdbc:postgresql://localhost/landmarkist
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
  flyway:
    locations: classpath:/db/migration,classpath:/db/data
